### ISSUE TITLE
Not sure if you could help

### ISSUE THREAD

**Issue by akhilleusuggo** [Petelombardo/vp9-encode-distributed#1]
When running the bench
```

./vp9-encode-distributed /mnt/my_ftp/test1.mp4 benchmark
./vp9-encode-distributed: line 73: /mnt/my_ftp//ffmpeg.benchmark: Operation not supported
./vp9-encode-distributed: line 73: /mnt/my_ftp//ffmpeg.benchmark: Operation not supported
```
When running the actual encoding

```
./vp9-encode-distributed /mnt/my_ftp/test1.mp4
Processing file /mnt/my_ftp/test1.mp4; Folder: /mnt/my_ftp/; File: test1.mp4
Resolution is 1080; Setting bitrate to 2500K
Duration: 00:05:20.46
Total seconds: 320
./vp9-encode-distributed: line 205: /mnt/my_ftp//test1.mp4.txt: Operation not supported
./vp9-encode-distributed: line 206: /mnt/my_ftp//test1.mp4.txt: Operation not supported
./vp9-encode-distributed: line 223: SLICE/TOTALUNITS: division by 0 (error token is "TOTALUNITS")
```

**Comment by Petelombardo** [comment]
Does the user running the script have write permissions to the folder where
the video is?

What happens if you change directories into the folder with the video and
then run the script?

Thanks,
-Pete

**Comment by akhilleusuggo** [comment]
@Petelombardo Hello,

Are you referring to master node or slaves nodes ( worker nodes ) ?

> What happens if you change directories into the folder with the video and then run the script?

Do you mean to move the script to the shared folder?

**Comment by Petelombardo** [comment]
I am referring to the master node.

The script does not need to run from the shared folder.

As the user running the script, can you run: touch
/mnt/my_ftp//ffmpeg.benchmark.test

Does it allow you to create that file?

Thanks,
-Pete

**Comment by Petelombardo** [comment]
FYI - I am firing up  a couple of test systems just to see if this script
still works with the latest version of Ubuntu.   It has been a couple of
years since I last updated it.  I want to make sure there are no bugs to
fix (there very well could be).

**Comment by akhilleusuggo** [comment]
touch does work. Output of the dir.

```
$ ls
ffmpeg.benchmark  ffmpeg.benchmark.test  test1.mp4  test1.mp4.join  test1.mp4.txt
```

**Comment by Petelombardo** [comment]
Worked for me using Ubuntu 21.04.

Here's what I did.

   - Created two VMs called media1 and media2
   - apt update; apt install ffmpeg git sshfs
   - On media1, I downloaded the vp9-encode-distributed script and chmod +x
   it to make it executable (stored it at /root/vp9-encode-distributed)
   - I edited /etc/ssh/sshd_config and changed PermitRootLogon to yes, then
   ran service ssh restart
   - On both media1 and media2, I ran ssh-keygen
   - I then ran ssh-copy-id media1 followed by ssh-copy-id media2
   - I created a folder on both VMs called /mnt/movies
   - I copied the movie to convert to media1:/mnt/movies
   - On media2, I ran sshfs media1:/mnt/movies /mnt/movies
   - Finally, on media1 I ran ./vp9-encode-distributed
   /mnt/movies/my-movie.mp4 benchmark
   - After that finished, I ran ./vp9-encode-distributed
   /mnt/movies/my-movie.mp4
   - I then checked the status with ./vp9-encode-distributed
   /mnt/movies/my-movie.mp4 status

When it completes, I'll run:
./vp9-encode-distributed /mnt/movies/my-movie.mp4 join

**Comment by Petelombardo** [comment]
Could the problem be how your servers are defined?   Here's what my servers
variable looks like.

SERVERS="media1.local media2.local"; # List your servers here (separated by
spaces)

**Comment by akhilleusuggo** [comment]
There are only 2 ways to define the servers:

on `.ssh/config`
or on `/etc/hosts`

mine is on `.ssh/config`

I run on terminal `ssh node1` , and it does log me in without pass promote or anything.

Anyway I appreciate that you took the time to look into it. I'll keep debugging by myself since you confirmed that it works. That only leaves the option that I am miss-configuring something.
